### ISSUE TITLE
Snapshot output seems noisy; are we emitting needlessly redundant references?

### ISSUE THREAD

**Issue by varungandhi-src** [sourcegraph/scip-typescript#152]
If you run `scip snapshot` on the index generated from running scip-typescript on itself, the output you get for FileIndexer.ts starts with:

```
  import * as ts from 'typescript'
//            ^^ reference scip-typescript npm typescript 4.6.2 lib/typescript.d.ts/ts/
//            ^^ reference scip-typescript npm typescript 4.6.2 lib/typescript.d.ts/ts/
//            ^^ reference scip-typescript npm typescript 4.6.2 lib/typescript.d.ts/ts/
//            ^^ reference scip-typescript npm typescript 4.6.2 lib/typescript.d.ts/ts/
//            ^^ reference scip-typescript npm typescript 4.6.2 lib/typescript.d.ts/ts/
//            ^^ reference scip-typescript npm typescript 4.6.2 lib/typescript.d.ts/ts/
//            ^^ reference scip-typescript npm typescript 4.6.2 lib/typescript.d.ts/ts/
//            ^^ reference scip-typescript npm typescript 4.6.2 lib/typescript.d.ts/ts/
//            ^^ reference scip-typescript npm typescript 4.6.2 lib/typescript.d.ts/ts/
//            ^^ reference scip-typescript npm typescript 4.6.2 lib/typescript.d.ts/ts/
//            ^^ reference scip-typescript npm typescript 4.6.2 lib/typescript.d.ts/ts/
//            ^^ reference scip-typescript npm typescript 4.6.2 lib/typescript.d.ts/ts/
//            ^^ reference scip-typescript npm typescript 4.6.2 lib/typescript.d.ts/ts/
//            ^^ reference scip-typescript npm typescript 4.6.2 lib/typescript.d.ts/ts/
//            ^^ reference scip-typescript npm typescript 4.6.2 lib/typescript.d.ts/ts/
//            ^^ reference scip-typescript npm typescript 4.6.2 lib/typescript.d.ts/ts/
//            ^^ reference scip-typescript npm typescript 4.6.2 lib/typescript.d.ts/ts/
//            ^^ reference scip-typescript npm typescript 4.6.2 lib/typescript.d.ts/ts/
//            ^^ reference scip-typescript npm typescript 4.6.2 lib/typescript.d.ts/ts/
```

Are we emitting one reference per use of `ts` in the file? 😅 This should probably get compressed away, but it'd be nice to avoid doing the work in the first place.

**Comment by valerybugakov** [comment]
@varungandhi-src, @olafurpg, the issue here comes from the fact that `ts` doesn't have one definition. The `ts` variable wraps all the exports from the `typescript` package into one variable via [the namespace import](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import#namespace_import). Definitions for underlying exports are located in multiple files internally, and types are grouped by multiple [Typescript namespaces](https://www.typescriptlang.org/docs/handbook/namespaces.html#multi-file-namespaces). 

<img width="1188" alt="Screenshot 2022-10-24 at 18 18 52" src="https://user-images.githubusercontent.com/3846380/197504467-fee833d7-d494-4497-aee7-fca903620df1.png">

The correct way to fix this would be to list links to all namespaces located in the same file but on different lines. Is it possible with [the current Symbol structure](https://github.com/sourcegraph/scip/blob/main/scip.proto#L97), or should we only aim to remove duplicates?

**Comment by varungandhi-src** [comment]
I would expect the following behavior from the index:
- The SCIP index should have multiple definition occurrences, one for each `namespace ts` block, and a single `SymbolInformation` for that namespace. It should not be emitting one SymbolInformation for each block (IDK if it is doing that, but if it is, that seems undesirable IMO).
- In the import statement, there should be a single reference occurrence.

 Does that make sense? The frontend should already be able to handle multiple definitions for an entity -- there shouldn't be a need to emit multiple references.

**Comment by olafurpg** [comment]
+1 to @varungandhi-src 's proposal. There should only be one reference occurrence, and multiple definition occurrences (plus a single `SymbolInformation`).

**Comment by valerybugakov** [comment]
Had a quick call with @varungandhi-src, will look into the implementation this week 👍
